### PR TITLE
update illuminance on occupancy state change

### PR DESCRIPTION
**Pull request by santalucial**
if you make automations that checks illuminance before turning on lights, and the occupancy goes off while you are in the room (which happens very often even with maximum sensitivity), no amount of waving will turn the light back on since the illuminance sensor has likely not picked the change up yet, and you are stuck with the lights off since now the occupancy is occupied and won't trigger automations again.

### CODE REVIEW

**Comment by santalucial** [comment]
arguable wether it should only update on the occupancy state or also on pir and mmwave sensors update, i myself use only the mmwave sensor for occupancy to avoid picking up pets in one room

**Comment by santalucial** [comment]
yesterday i installed one in the bedroom, in a corner at 2 meters height, 1.5 meters from me, this is the occupancy history.
image
The settings are:
- mmWave Distance = 405
- mmWave Off Latency = 30
- mmWave On Latency = 1
- mmWave Sensitivity = 7

**Comment by giannoug** [comment]
@EverythingSmartHome Consider the following scenario:
- You enter the room: occupancy=true, lux=500 - Light turns on due to occupancy
- You leave the room: occupancy=false, lux=500 - Light stays on due to timer
- Lights turn off after 5m: occupancy=false, lux=500 light - Light turns off due to timer
- You immediately enter the room: occupancy=true, lux=500 - Light stays off due to high lux value

Lights won't turn off since the sensor thinks the room is bright enough. I believe this PR needs to be merged, this is how other sensors work. For example Hue: https://community.home-assistant.io/t/deconz-hue-motion-sensor-light-level-not-updating-after-change/226130/3

**Comment by crhammock** [comment]
I think I have this same problem.  Looks like the lux sensor updates every 30 seconds so if my lights happen to go off due to occupancy delay and I re-enter the room in that 30 second window, I am walking around in the dark.  The suggestion to update the lux sensor when the occupancy, mmwave or pir state changes seems like a good solution.

I am guessing we can't get the sensor to update realtime

When will this fix be implemented, its not getting any lighter outside :)

**Comment by T1ppes** [comment]
Lux value update on occupancy/PIR/mm wave state change would be perfect.

**Comment by dnedeltchev** [comment]
The way u solved that problem is to change the timeout on the lux sensor to 1 second which pretty much solves this problem. Of course it's pointless getting lux every second especially at night and when there is no motion but it does the trick for me.
Lewis helped with that on discord
Add
illuminance_update_interval: "1s"
Under substitutions in the yaml, install, reboot (not sure if reboot is needed but I did anyway) and job done.

**Comment by santalucial** [comment]
That's a buggy solution especially if the light turns off on you and you start waving within that second, very dependant on your reaction time and the randomness of the time left for the next update

**Comment by dnedeltchev** [comment]
Buggy? How so? A bit ott but it does exactly what a lux update on PIR trigger would do. I have the light turn off after 5 min of no occupation (which includes the mmwave sensor). Lux updates every second so as soon as PIR goes idle, lux updates and subsequent triggering the PIR turns on the light with relevant lux level. It's been almost a week and it's not failed once.

**Comment by crhammock** [comment]
maybe buggy isn't the right word.  The key is obviously knowing the lux level at the exact same time as the occupancy state.  Updating the lux every second brings you closer to that goal but it feels more like a work around than a solution.

I will definitely give it a try as I am sure it will reduce the issue significantly.

I am not familiar with ESP coding but it seems like the fix to update the lux at the same time as the occupancy has already been committed, its 3 lines of code does it just need applying at the next update?

**Comment by EverythingSmartHome** [comment]
I'm not sure if this will help or not, since I think motion will be triggered, thus starting any automations and then a light level update will happen after making it too late. However, there would be no harm in trying it.

**Comment by dnedeltchev** [comment]
> I'm not sure if this will help or not, since I think motion will be triggered, thus starting any automations and then a light level update will happen after making it too late. However, there would be no harm in trying it.

I have the same issue with Zigbee sensors. Even though they provide lux when motion is triggered, motion always comes before lux so I have to add a few milliseconds delay in my node red before I check lux. I think changing the lux reporting to 1 second is the way to go, for me at least. Unless there is some negative impact on the sensor from sending lux every second?

**Comment by crhammock** [comment]
I updated my EP1 and set the illuminance_update_interval to 1 hour just for testing.  Exactly as @dnedeltchev says the lux update always comes 1 second after the occupancy update, not sure if this is an issue with the ESP code or the HA code.  I don't understand the code enough or the update process to grasp why this would be the case and how to resolve it.   Seems to me if its consistent (which it is) then it must be possible to reverse so the lux comes before occupancy or get them received and processed at the same time.

For now I have had no issues with just setting the update interval to 1 second.  But if anyone wants to make further modifications I will be happy to test

**Comment by nstrelow** [comment]
@EverythingSmartHome this change is missing in the beta.yml file :)

Not sure if it should be there as well

**Comment by EverythingSmartHome** [comment]
> Reference

No this is expected as I guessed above, it's because as soon as a state changes in ESPHome, it will send the updated value immediately which is the best for speed and responsiveness.

Delaying sending the motion event would make turning lights on slower than they need to be

**Comment by EverythingSmartHome** [comment]
> @EverythingSmartHome this change is missing in the beta.yml file :)
> 
> Not sure if it should be there as well

No it still needs adding, thanks!

**Pull request merged**
