### PR TITLE
Distance sensor

### PR DESCRIPTION
**Pull request by Grummle**
This isn't a working pull request as I don't have an EP1 to work with. I was able to get the SEN0395 to report a decent distance for the target. 
It cycles through all the targets and uses the one with the best S/N ratio. 
Using one in my bathroom to turn on the exhaust fan if you are a certain distance away after 2 min. Meaning your on the toliet or in the shower, Closer and you'd be at the sink.
I *cough* borrowed alot of your settings for mine so figured I'd give back what I could. 
https://www.printables.com/model/479349-dfrobot-millimeter-wave-radar-enclosure

### CODE REVIEW

**Comment by Grummle** [comment]
right you are, forgot you have to enable "uart_target_output" by default so that it'll have something to parse. I've updated the pull request.

**Comment by Grummle** [comment]
something I ran into when debugging, and I realize this sounds weird, if there is alot of logging. Like the Uart debug logging it doesn't actually parse the first several JYRPO targets. Like 1-4.

**Comment by Grummle** [comment]
also this is the first C I've written in 20 years so no guarantees :P

**Comment by Grummle** [comment]
I updated the yaml to remove the UART logging you had. I added in more logging on the last index of the loop.
It 'works' but why its so sensitive to other logging I'm not sure.


```
[11:06:49][D][sensor:110]: 'Target Distance m': Sending state 1.46900  with 5 decimals of accuracy
[11:06:49][D][custom:093]: 1.656000, 0.469000, 0.313000, 0.813000, 1.031000, 3.594000, 0.000000, 0.000000, 0.000000
[11:06:49][D][custom:094]: 1.469000, 2.547000, 2.547000, 2.023000, 2.547000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:49][D][custom:094]: Distance: 1.469000
[11:06:49][D][custom:095]: SNR: 1.656000
[11:06:49][D][custom:096]: Distance: 1.469000
[11:06:49][D][custom:097]: idx: 1
[11:06:50][D][sensor:110]: 'Target Distance m': Sending state 1.44500  with 5 decimals of accuracy
[11:06:50][D][custom:093]: 1.313000, 0.438000, 0.313000, 0.813000, 1.031000, 3.594000, 0.000000, 0.000000, 0.000000
[11:06:50][D][custom:094]: 1.445000, 2.547000, 2.547000, 2.023000, 2.547000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:50][D][custom:094]: Distance: 1.445000
[11:06:50][D][custom:095]: SNR: 1.313000
[11:06:50][D][custom:096]: Distance: 1.445000
[11:06:50][D][custom:097]: idx: 1
[11:06:52][D][sensor:110]: 'Target Distance m': Sending state 1.39800  with 5 decimals of accuracy
[11:06:53][D][custom:093]: 1.438000, 0.438000, 0.313000, 0.813000, 1.031000, 3.594000, 0.000000, 0.000000, 0.000000
[11:06:54][D][custom:094]: 1.398000, 2.547000, 2.547000, 2.023000, 2.547000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:54][D][custom:094]: Distance: 1.398000
[11:06:54][D][custom:095]: SNR: 1.438000
[11:06:54][D][custom:096]: Distance: 1.398000
[11:06:54][D][custom:097]: idx: 1
[11:06:54][D][sensor:110]: 'Target Distance m': Sending state 0.73400  with 5 decimals of accuracy
[11:06:54][D][custom:093]: 29.469000, 4.188000, 2.094000, 1.031000, 1.031000, 3.594000, 0.000000, 0.000000, 0.000000
[11:06:54][D][custom:094]: 0.734000, 1.500000, 1.992000, 2.547000, 2.547000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:54][D][custom:094]: Distance: 0.734000
[11:06:54][D][custom:095]: SNR: 29.469000
[11:06:54][D][custom:096]: Distance: 0.734000
[11:06:54][D][custom:097]: idx: 1
[11:06:54][D][sensor:110]: 'Target Distance m': Sending state 0.73400  with 5 decimals of accuracy
[11:06:54][D][custom:093]: 44.813000, 4.375000, 4.406000, 2.563000, 1.031000, 3.594000, 0.000000, 0.000000, 0.000000
[11:06:54][D][custom:094]: 0.734000, 1.578000, 2.109000, 2.547000, 2.547000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:54][D][custom:094]: Distance: 0.734000
[11:06:54][D][sensor:110]: 'Target Distance m': Sending state 0.74200  with 5 decimals of accuracy
[11:06:55][D][sensor:110]: 'Target Distance m': Sending state 0.73400  with 5 decimals of accuracy
[11:06:55][D][custom:093]: 42.155998, 14.500000, 5.906000, 3.750000, 1.031000, 3.594000, 0.000000, 0.000000, 0.000000
[11:06:55][D][custom:094]: 0.734000, 2.266000, 2.547000, 2.547000, 2.547000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:55][D][custom:094]: Distance: 0.734000
[11:06:55][D][custom:095]: SNR: 42.155998
[11:06:55][D][custom:096]: Distance: 0.734000
[11:06:55][D][custom:097]: idx: 1
[11:06:57][D][sensor:110]: 'Target Distance m': Sending state 0.74200  with 5 decimals of accuracy
[11:06:58][D][custom:093]: 19.000000, 34.938000, 11.531000, 6.344000, 1.031000, 3.594000, 0.000000, 0.000000, 0.000000
[11:06:59][D][custom:094]: 0.320000, 0.742000, 2.281000, 2.547000, 2.547000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:59][D][custom:094]: Distance: 0.742000
[11:06:59][D][custom:095]: SNR: 34.938000
[11:06:59][D][custom:096]: Distance: 0.742000
[11:06:59][D][custom:097]: idx: 2
[11:06:59][D][sensor:110]: 'Target Distance m': Sending state 0.68800  with 5 decimals of accuracy
[11:06:59][D][custom:093]: 16.281000, 39.469002, 4.156000, 8.938000, 4.031000, 3.594000, 0.000000, 0.000000, 0.000000
[11:06:59][D][custom:094]: 0.211000, 0.688000, 1.820000, 2.250000, 2.547000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:59][D][custom:094]: Distance: 0.688000
[11:06:59][D][custom:095]: SNR: 39.469002
[11:06:59][D][custom:096]: Distance: 0.688000
[11:06:59][D][custom:097]: idx: 2
[11:06:59][D][sensor:110]: 'Target Distance m': Sending state 0.63300  with 5 decimals of accuracy
[11:06:59][D][custom:093]: 16.500000, 32.344002, 19.563000, 4.969000, 6.813000, 2.969000, 0.000000, 0.000000, 0.000000
[11:06:59][D][custom:094]: 0.188000, 0.633000, 1.180000, 1.758000, 2.211000, 2.547000, 0.000000, 0.000000, 0.000000
[11:06:59][D][custom:094]: Distance: 0.633000
[11:06:59][D][sensor:110]: 'Target Distance m': Sending state 0.62500  with 5 decimals of accuracy
[11:07:00][D][sensor:110]: 'Target Distance m': Sending state 0.61700  with 5 decimals of accuracy
[11:07:00][D][custom:093]: 11.500000, 23.000000, 15.781000, 4.625000, 3.813000, 1.469000, 0.000000, 0.000000, 0.000000
[11:07:00][D][custom:094]: 0.172000, 0.617000, 1.203000, 1.766000, 2.141000, 2.547000, 0.000000, 0.000000, 0.000000
[11:07:00][D][custom:094]: Distance: 0.617000
[11:07:00][D][custom:095]: SNR: 23.000000
[11:07:00][D][custom:096]: Distance: 0.617000
```

**Comment by v00g100skr** [comment]
works but weird
tracked distance changing each time in all range diapazone from 0.5 to sensor max distanse from settings

**Comment by EverythingSmartHome** [comment]
Got some time to test it tonight, works good but like you mentioned, need to disable the UART debugging, wonder why that is?

Do you think it would be reasonably easy to add say, 4 targets, in order of best SNR?

**Comment by Grummle** [comment]
Yeah easy peasy. Had it that way originally. 8 is to many it bombs after a
couple min.

**Comment by EverythingSmartHome** [comment]
I used 4 for a while a few months back (although without the selecting based on best SNR) and seemed to be fine, but can give it a best test to see if it's reliable!

**Comment by Grummle** [comment]
Think the instability comes from the polling rate * targets + HA updates.

**Comment by EverythingSmartHome** [comment]
@Grummle Do you think you would have some time to add 4 targets in order of best SNR? If not I can try give it a shot in a while.

Be good to get this together then add it to a beta firmware for other users to test!

**Comment by Grummle** [comment]
Honestly probably not. Don’t have your sensor and I don’t have any interest in 4 targets.

**Review by EverythingSmartHome — COMMENTED** [review]
Moved the changes from the main firmware file to it's own dedicated beta file to allow for bigger changes such as this, plus future additions. Also moved the distance sensor to the correct sensor section and removed duplicate.

**Comment by EverythingSmartHome** [comment]
Thanks again for adding that!

**Comment by BradleyFord** [comment]
How confident are we in the distance reading?
Mine is installed in my ceiling (which is 3 meters high), I am sitting directly beneath and the result is between 3m to 3.5m

**Comment by EverythingSmartHome** [comment]
> How confident are we in the distance reading? Mine is installed in my ceiling (which is 3 meters high), I am sitting directly beneath and the result is between 3m to 3.5m

Generally it's pretty good. But since yours is in your ceiling then this sensor probably won't be all that useful to you in comparison to wall mounted

**Comment by BradleyFord** [comment]
It seems to have settled down a bit now, but some smoothing might be in order...

When sitting it is very consistent at about 1.8m which should be about right; but it jumps to 3m for a tiny amount of time before going back to 1.8m.
I think if we can smooth it out over 1s or even 0.5s it should then be very stable.

**Comment by EverythingSmartHome** [comment]
> It seems to have settled down a bit now, but some smoothing might be in order...
> 
> When sitting it is very consistent at about 1.8m which should be about right; but it regularly jumps to 3m for a tiny amount of time before going back to 1.8m. I think if we can smooth it out over 1s or even 0.5s it should then be very stable.

All of the calculation for that is done in the mmWave sensors firmware so no way to access it. This PR just reads what was already being outputted and makes it available in HA.

Though perhaps we could add a median or moving average filter in ESPHome to combat. I'd be interested to hear if other users are experiencing that who don't have it ceiling mounted however

**Comment by ChaconC** [comment]
> Though perhaps we could add a median or moving average filter in ESPHome to combat. I'd be interested to hear if other users are experiencing that who don't have it ceiling mounted however

Chiming in here:
The measurements as currently implemented are almost impossible to use when sitting for a while.

The distance from my sensor to my chair is around 2.0-2.1, which is properly measured. When I'm sitting and not paying much attention, it appears to be taking the round trip value.
CleanShot 2023-07-21 at 11 38 41

I do believe an average would help as I can see a bit of a pattern when I'm sitting (green) vs when I left my office for a short time (red).
CleanShot 2023-07-21 at 11 41 55

**Comment by EverythingSmartHome** [comment]
@ChaconC @BradleyFord Can you try the latest firmware? This one doesn't sort by highest SNR as I wondered if that was causing it to flip back and forth between two targets, resulting in the sudden spikes your seeing. Be interested to know if that helps!

**Comment by BradleyFord** [comment]
> @ChaconC @BradleyFord Can you try the latest firmware? This one doesn't sort by highest SNR as I wondered if that was causing it to flip back and forth between two targets, resulting in the sudden spikes your seeing. Be interested to know if that helps!

I am installing it in my office and .... the toilet. The best testing locations :)

**Comment by ChaconC** [comment]
> @ChaconC @BradleyFord Can you try the latest firmware? This one doesn't sort by highest SNR as I wondered if that was causing it to flip back and forth between two targets, resulting in the sudden spikes your seeing. Be interested to know if that helps!

Updating now, will come back in a bit!

**Pull request merged**
